trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'xslt.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    packageType: sdk
    useGlobalJson: true
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    feedsToUse: 'config'
    nugetConfigPath: './nuget.config'
- task: DotNetCoreCLI@2
  displayName: 'Build Windows .NET 4.7.2'
  inputs:
    command: 'build'
    projects: './xslt/netfx/xslt-netfx.csproj'
    arguments: '-c $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/net472/'
- task: DotNetCoreCLI@2
  displayName: 'Build Windows .NET Core'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: './xslt/netcore/xslt-netcore.csproj'
    arguments: '-c $(buildConfiguration) -r win-x64 --output $(Build.ArtifactStagingDirectory)/win-x64/ /p:PublishSingleFile=true /p:PublishTrimmed=true'
- task: DotNetCoreCLI@2
  displayName: 'Build Linux .NET Core'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: './xslt/netcore/xslt-netcore.csproj'
    arguments: '-c $(buildConfiguration) -r linux-x64 --output $(Build.ArtifactStagingDirectory)/linux-x64/ /p:PublishSingleFile=true /p:PublishTrimmed=true'        
- task: ArchiveFiles@2
  displayName: 'Zip .NET 4.7.2 Build'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/net472/xslt.exe'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/binaries/xslt-net472.zip'
    replaceExistingArchive: true
    verbose: true  
- task: ArchiveFiles@2
  displayName: 'Zip Windows x64 Build'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/win-x64/netcore/xslt.exe'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/binaries/xslt-win.zip'
    replaceExistingArchive: true
    verbose: true      
- task: ArchiveFiles@2
  displayName: 'Zip Linux x64 Build'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/linux-x64/netcore/xslt'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/binaries/xslt-linux.zip'
    replaceExistingArchive: true
    verbose: true          
- task: PublishBuildArtifacts@1
  displayName: Publish Packages as Build Artifacts
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/binaries
    ArtifactName: addup-xslt-binaries
    publishLocation: Container