name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-linux:
    runs-on: windows-2019
    steps:
    - name: Define global variables
      uses: allenevans/set-env@v1.0.0
      with:
        SOLUTION: 'xslt.sln'
        BUILD_CONFIGURATION: 'Release'
        PRERELEASE_SUFFIX: 'alpha'  
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install Sonar
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Restore
      run: dotnet restore ${SOLUTION} --configfile ./nuget.config
    - name: Sonar Begin
      run: dotnet sonarscanner begin /k:"addup-xslt"  /n:"addup-xslt" /o:"addupsolutions-oss" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.verbose=true /d:sonar.host.url=https://sonarcloud.io 
    - name: Build
      run: dotnet build ${SOLUTION} --configuration ${BUILD_CONFIGURATION} --no-restore
    - name: Test
      run: dotnet test ${SOLUTION} --configuration ${BUILD_CONFIGURATION} --no-build --no-restore --verbosity normal
    - name: Sonar end
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
